/** Declaration file generated by dts-gen */
declare module 'gists' {
    export = Gists;

    declare class Gists {
        constructor(...args: any[]);

        all(...args: any[]): any;

        commits(...args: any[]): any;

        create(...args: any[]): any;

        createComment(...args: any[]): any;

        delete(...args: any[]): any;

        deleteComment(...args: any[]): any;

        edit(...args: any[]): any;

        editComment(...args: any[]): any;

        fork(...args: any[]): any;

        forks(...args: any[]): any;

        get(...args: any[]): any;

        getComment(...args: any[]): any;

        isStarred(...args: any[]): any;

        list(...args: any[]): any;

        listComments(...args: any[]): any;

        public(...args: any[]): any;

        revision(...args: any[]): any;

        star(...args: any[]): any;

        starred(...args: any[]): any;

        unstar(...args: any[]): any;

    }
}
